select *from customer

--Q1. What is the total revenue generated by male vs. female customers?
SELECT
    gender,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    customer_id,
    gender,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount >
      (SELECT AVG(purchase_amount)
       FROM customer);

--Q3. Which are the top 5 products with the highest average review rating?

SELECT
    item_purchased,
   AVG(review_rating)AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    shipping_type,
    ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status,
    ROUND(AVG(purchase_amount),2) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,

    ROUND(
        100.0 * SUM(
            CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS discount_percentage

FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    customer_segment,
    COUNT(*) AS customer_count
FROM
(
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases <= 5 THEN 'New'
            WHEN previous_purchases <= 20 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) t
GROUP BY customer_segment
ORDER BY customer_count DESC;

--Q8. What are the top 3 most purchased products within each category?
WITH product_sales AS
(
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_purchases,

        RANK() OVER
        (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS product_rank

    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    total_purchases,
    product_rank
FROM product_sales
WHERE product_rank <= 3
ORDER BY category, product_rank;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id)
from customer
where previous_purchases>=5
group by subscription_status


--Q10. What is the revenue contribution of each age group?
select sum(purchase_amount),age_group 
from customers
group by age_group


